### ISSUE TITLE
Add architecture awareness to build/example script

### ISSUE THREAD

**Issue by aetimmes** [DataDog/nginx-datadog#15] opened 2023-03-02 14:48 UTC
I'm attempting to run `example/bin/run` on a M1 Macbook for local development, but am receiving the following error:

```docker
example-agent-1    | starting trace-agent
example-agent-1    | starting system-probe
example-agent-1    | starting process-agent
example-agent-1    | starting security-agent
example-agent-1    | [services.d] done.
example-agent-1    | starting agent
example-agent-1    | WARNING: `--config` argument is deprecated and will be removed in a future version. Please use `--cfgpath` instead.
example-http-1     | http node.js web server is running
example-fastcgi-1  | fastcgi node.js web server is running
example-nginx-1    | 2023/03/02 14:41:48 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_datadog_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_datadog_module.so: unsupported relocation type 7) in /etc/nginx/nginx.conf:2
example-nginx-1    | nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_datadog_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_datadog_module.so: unsupported relocation type 7) in /etc/nginx/nginx.conf:2
example-grpc-1     | gRPC node server is about to run
example-nginx-1 exited with code 1
Aborting on container exit...
```

If I pull down the module from the DataDog release used in the build step, I get an x86_64 binary, which I'm guessing is the reason for the .so relocation error:

```bash
$ wget 'https://github.com/DataDog/nginx-datadog/releases/download/v0.5.3/nginx_1.23.3-ngx_http_datadog_module.so.tgz' > /dev/null 2>&1
$ tar xzvf 'nginx_1.23.3-ngx_http_datadog_module.so.tgz'
x ngx_http_datadog_module.so
$ file ngx_http_datadog_module.so
ngx_http_datadog_module.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=4d3cf7bc0ad0e51473ba7002b36b6887e8007078, with debug_info, not stripped
```

It would be nice if the example script worked out of the box for ARM local dev. (I can work around it with the local build scripts; it'd just be nice to have.)

**Comment by dgoffredo** [comment] 2023-05-31 21:42
Thanks for reporting this. My colleagues at Datadog have pointed out the same issue.

Part of the problem is that the example serves two purposes. The first purpose is to be... an example. For this, a local build would suffice. The second purpose is to serve as an almost-copy-paste template for supported usage of the module. For this, downloading a `.so` from a GitHub release is better. The problem then is that our release artifacts include builds for x86_64 only (for now), since that's where reverse proxies are running in production (for now).

What do you think is a better way for the `example/` to work?

**Comment by phillipuniverse** [comment] 2023-09-01 21:34
I got a slightly different error message, including here for other people that might find this thread:

```
public-gateway-gateway-1  | 2023/09/01 17:12:53 [emerg] 28#28: dlopen() "/etc/nginx/modules/ngx_http_datadog_module.so" failed (/etc/nginx/modules/ngx_http_datadog_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/common-outer-config.nginx.conf:30
public-gateway-gateway-1  | nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_datadog_module.so" failed (/etc/nginx/modules/ngx_http_datadog_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/common-outer-config.nginx.conf:30
```

That's not from the example but from integrating the module into my own code. The `No such file or directory` really had me stumped for a while.

But the issue turned out to be the same, running on a Mac M2 with arm.

@aetimmes there is a simple way to make the example work by setting the `DOCKER_DEFAULT_PLATFORM` environment variable:

```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```

> What do you think is a better way for the example/ to work?

@dgoffredo perhaps an early failure that the example will not work if an arm architecture was detected? Or even forcing a `platform` in the `docker-compose.yml` for the nginx image, that will also force a hard fail.

The ideal scenario of course would be to have arm binaries available for download!

**Comment by dgoffredo** [comment] 2023-09-02 17:51
Thanks, Phillip. Early failure would be best. I'll look into `DOCKER_DEFAULT_PLATFORM` or an explicit `uname -m` check.

arm64 support would be even better. We have yet to do project planning for the 4th quarter -- let's see if that makes it in.

**Comment by dgoffredo** [comment] 2023-11-03 14:42
We're on ARM64 now. Not sure what that means for Apple silicon, but I'll close this issue. Feel free to reopen if there's more work to be done.

**Closed by dgoffredo** 2023-11-03 14:42 UTC
